import type { QuizData } from './types';

export const QUIZ_DATA: QuizData[] = [
  {
    lessonId: 'free-1',
    questions: [
      {
        id: 'f1q1',
        question: 'ما هو التيرمينال (Terminal)؟',
        questionEn: 'What is the Terminal?',
        options: ['واجهة رسومية لسطح المكتب', 'واجهة نصية للتفاعل مع نظام التشغيل', 'برنامج لتصفح الإنترنت', 'لعبة فيديو'],
        optionsEn: ['A graphical desktop interface', 'A text interface to interact with the OS', 'A web browser', 'A video game'],
        correct: 1,
      },
      {
        id: 'f1q2',
        question: 'ما معنى الرمز $ في التيرمينال؟',
        questionEn: 'What does the $ symbol mean in the terminal?',
        options: ['مستخدم عادي', 'مستخدم root', 'خطأ في النظام', 'مجلد جديد'],
        optionsEn: ['Regular user', 'Root user', 'System error', 'New folder'],
        correct: 0,
      },
      {
        id: 'f1q3',
        question: 'ما هو الاختصار لفتح التيرمينال في لينكس؟',
        questionEn: 'What is the shortcut to open Terminal in Linux?',
        options: ['Ctrl + C', 'Ctrl + V', 'Ctrl + Alt + T', 'Alt + F4'],
        optionsEn: ['Ctrl + C', 'Ctrl + V', 'Ctrl + Alt + T', 'Alt + F4'],
        correct: 2,
      },
      {
        id: 'f1q4',
        question: 'ماذا يعني الرمز ~ في المسار؟',
        questionEn: 'What does ~ mean in a path?',
        options: ['المجلد الجذر', 'المجلد الرئيسي للمستخدم', 'المجلد الحالي', 'المجلد السابق'],
        optionsEn: ['Root directory', 'Home directory', 'Current directory', 'Previous directory'],
        correct: 1,
      },
      {
        id: 'f1q5',
        question: 'أي من هذه الأوامر يظهر اسم المستخدم الحالي؟',
        questionEn: 'Which command shows the current username?',
        options: ['pwd', 'ls', 'whoami', 'date'],
        optionsEn: ['pwd', 'ls', 'whoami', 'date'],
        correct: 2,
      },
    ],
  },
  {
    lessonId: 'free-2',
    questions: [
      {
        id: 'f2q1',
        question: 'ما وظيفة الأمر pwd؟',
        questionEn: 'What does pwd do?',
        options: ['عرض محتويات المجلد', 'عرض المسار الحالي', 'تغيير المجلد', 'حذف مجلد'],
        optionsEn: ['List directory contents', 'Print working directory', 'Change directory', 'Delete directory'],
        correct: 1,
      },
      {
        id: 'f2q2',
        question: 'كيف تنتقل إلى المجلد الرئيسي (Home)؟',
        questionEn: 'How do you navigate to the Home directory?',
        options: ['cd /', 'cd ~', 'cd ..', 'cd home'],
        optionsEn: ['cd /', 'cd ~', 'cd ..', 'cd home'],
        correct: 1,
      },
      {
        id: 'f2q3',
        question: 'ماذا يفعل الأمر ls -a؟',
        questionEn: 'What does ls -a do?',
        options: ['عرض الملفات بالتفاصيل', 'عرض جميع الملفات بما فيها المخفية', 'عرض الملفات فقط', 'عرض المجلدات فقط'],
        optionsEn: ['List files with details', 'List all files including hidden', 'List files only', 'List directories only'],
        correct: 1,
      },
      {
        id: 'f2q4',
        question: 'كيف ترجع إلى المجلد الأب؟',
        questionEn: 'How do you go to the parent directory?',
        options: ['cd parent', 'cd ..', 'cd ~', 'cd /'],
        optionsEn: ['cd parent', 'cd ..', 'cd ~', 'cd /'],
        correct: 1,
      },
      {
        id: 'f2q5',
        question: 'أي أمر يعرض محتويات المجلد الحالي؟',
        questionEn: 'Which command lists directory contents?',
        options: ['pwd', 'cd', 'ls', 'cat'],
        optionsEn: ['pwd', 'cd', 'ls', 'cat'],
        correct: 2,
      },
    ],
  },
  {
    lessonId: 'free-3',
    questions: [
      {
        id: 'f3q1',
        question: 'ما الأمر المستخدم لإنشاء مجلد جديد؟',
        questionEn: 'Which command creates a new directory?',
        options: ['touch', 'mkdir', 'create', 'new'],
        optionsEn: ['touch', 'mkdir', 'create', 'new'],
        correct: 1,
      },
      {
        id: 'f3q2',
        question: 'كيف تنشئ ملفاً فارغاً؟',
        questionEn: 'How do you create an empty file?',
        options: ['create file.txt', 'new file.txt', 'touch file.txt', 'make file.txt'],
        optionsEn: ['create file.txt', 'new file.txt', 'touch file.txt', 'make file.txt'],
        correct: 2,
      },
      {
        id: 'f3q3',
        question: 'ما الفرق بين cp و mv؟',
        questionEn: 'What is the difference between cp and mv?',
        options: ['لا فرق', 'cp ينسخ و mv ينقل/يعيد تسمية', 'cp ينقل و mv ينسخ', 'cp يحذف و mv ينسخ'],
        optionsEn: ['No difference', 'cp copies, mv moves/renames', 'cp moves, mv copies', 'cp deletes, mv copies'],
        correct: 1,
      },
      {
        id: 'f3q4',
        question: 'ما الأمر الذي يحذف مجلد ومحتوياته بالكامل؟',
        questionEn: 'Which command deletes a folder and all its contents?',
        options: ['rm folder', 'rmdir folder', 'rm -rf folder', 'delete folder'],
        optionsEn: ['rm folder', 'rmdir folder', 'rm -rf folder', 'delete folder'],
        correct: 2,
      },
      {
        id: 'f3q5',
        question: 'كيف تنشئ مجلدات متداخلة (مجلد داخل مجلد)؟',
        questionEn: 'How do you create nested directories?',
        options: ['mkdir a/b', 'mkdir -p a/b/c', 'create a/b/c', 'md a/b/c'],
        optionsEn: ['mkdir a/b', 'mkdir -p a/b/c', 'create a/b/c', 'md a/b/c'],
        correct: 1,
      },
    ],
  },
  {
    lessonId: 'free-4',
    questions: [
      {
        id: 'f4q1',
        question: 'أي أمر يعرض محتوى ملف كاملاً؟',
        questionEn: 'Which command displays the full content of a file?',
        options: ['head', 'tail', 'cat', 'wc'],
        optionsEn: ['head', 'tail', 'cat', 'wc'],
        correct: 2,
      },
      {
        id: 'f4q2',
        question: 'ماذا يفعل head -n 20 file.txt؟',
        questionEn: 'What does head -n 20 file.txt do?',
        options: ['يعرض آخر 20 سطراً', 'يعرض أول 20 سطراً', 'يعرض 20 كلمة', 'يحذف 20 سطراً'],
        optionsEn: ['Shows last 20 lines', 'Shows first 20 lines', 'Shows 20 words', 'Deletes 20 lines'],
        correct: 1,
      },
      {
        id: 'f4q3',
        question: 'أي أمر يستخدم لمتابعة السجلات في الوقت الفعلي؟',
        questionEn: 'Which command follows logs in real-time?',
        options: ['cat -f', 'head -f', 'tail -f', 'less -f'],
        optionsEn: ['cat -f', 'head -f', 'tail -f', 'less -f'],
        correct: 2,
      },
      {
        id: 'f4q4',
        question: 'ماذا يفعل الأمر wc؟',
        questionEn: 'What does wc do?',
        options: ['يعد الكلمات فقط', 'يعد الأسطر والكلمات والأحرف', 'يعرض عدد الملفات', 'يقارن ملفين'],
        optionsEn: ['Counts only words', 'Counts lines, words, and characters', 'Shows file count', 'Compares two files'],
        correct: 1,
      },
      {
        id: 'f4q5',
        question: 'كيف تخرج من برنامج less؟',
        questionEn: 'How do you exit the less program?',
        options: ['exit', 'q', 'quit', 'Ctrl+C'],
        optionsEn: ['exit', 'q', 'quit', 'Ctrl+C'],
        correct: 1,
      },
    ],
  },
  {
    lessonId: 'free-5',
    questions: [
      {
        id: 'f5q1',
        question: 'ماذا يعني rwx في صلاحيات الملفات؟',
        questionEn: 'What does rwx mean in file permissions?',
        options: ['تشغيل-كتابة-تنفيذ', 'قراءة-كتابة-تنفيذ', 'قراءة-تنفيذ-حذف', 'إعادة-كتابة-حذف'],
        optionsEn: ['Run-Write-Execute', 'Read-Write-Execute', 'Read-Execute-Delete', 'Rewrite-Execute-Delete'],
        correct: 1,
      },
      {
        id: 'f5q2',
        question: 'ما معنى الرقم 755 في chmod 755؟',
        questionEn: 'What does 755 mean in chmod 755?',
        options: ['rwxr--r--', 'rwxr-xr-x', 'rw-rw-rw-', 'rwx------'],
        optionsEn: ['rwxr--r--', 'rwxr-xr-x', 'rw-rw-rw-', 'rwx------'],
        correct: 1,
      },
      {
        id: 'f5q3',
        question: 'كيف تضيف صلاحية التنفيذ لملف؟',
        questionEn: 'How do you add execute permission to a file?',
        options: ['chmod +r file', 'chmod +w file', 'chmod +x file', 'chmod +e file'],
        optionsEn: ['chmod +r file', 'chmod +w file', 'chmod +x file', 'chmod +e file'],
        correct: 2,
      },
      {
        id: 'f5q4',
        question: 'ما وظيفة الأمر chown؟',
        questionEn: 'What does chown do?',
        options: ['يغير الصلاحيات', 'يغير المالك والمجموعة', 'يغير كلمة المرور', 'يحذف مستخدم'],
        optionsEn: ['Changes permissions', 'Changes owner and group', 'Changes password', 'Deletes user'],
        correct: 1,
      },
      {
        id: 'f5q5',
        question: 'أي أمر يضيف مستخدم جديد؟',
        questionEn: 'Which command adds a new user?',
        options: ['adduser', 'useradd', 'newuser', 'mkuser'],
        optionsEn: ['adduser', 'useradd', 'newuser', 'mkuser'],
        correct: 1,
      },
    ],
  },
  {
    lessonId: 'free-6',
    questions: [
      {
        id: 'f6q1',
        question: 'ما وظيفة الأمر grep؟',
        questionEn: 'What does grep do?',
        options: ['يعرض الملفات', 'يبحث عن أنماط في النصوص', 'يقارن ملفين', 'يحذف كلمات'],
        optionsEn: ['Displays files', 'Searches for patterns in text', 'Compares two files', 'Deletes words'],
        correct: 1,
      },
      {
        id: 'f6q2',
        question: 'كيف تبحث عن كلمة "error" متجاهلاً حالة الأحرف؟',
        questionEn: 'How do you search for "error" case-insensitively?',
        options: ['grep "error" file', 'grep -i "error" file', 'grep -c "error" file', 'grep -v "error" file'],
        optionsEn: ['grep "error" file', 'grep -i "error" file', 'grep -c "error" file', 'grep -v "error" file'],
        correct: 1,
      },
      {
        id: 'f6q3',
        question: 'ماذا يفعل grep -r؟',
        questionEn: 'What does grep -r do?',
        options: ['يبحث بشكل عكسي', 'يبحث في كل المجلدات الفرعية', 'يبحث بعدد محدد', 'يبحث في ملف واحد'],
        optionsEn: ['Reverse search', 'Searches recursively in subdirectories', 'Search with count', 'Search single file'],
        correct: 1,
      },
      {
        id: 'f6q4',
        question: 'كيف تبحث عن سطور تبدأ بكلمة "Start"؟',
        questionEn: 'How do you search for lines starting with "Start"?',
        options: ['grep "Start" file', 'grep "^Start" file', 'grep "Start$" file', 'grep "[Start]" file'],
        optionsEn: ['grep "Start" file', 'grep "^Start" file', 'grep "Start$" file', 'grep "[Start]" file'],
        correct: 1,
      },
      {
        id: 'f6q5',
        question: 'أي أمر يبحث عن ملفات باسم معين؟',
        questionEn: 'Which command finds files by name?',
        options: ['grep -name', 'find -name', 'locate -name', 'search -name'],
        optionsEn: ['grep -name', 'find -name', 'locate -name', 'search -name'],
        correct: 1,
      },
    ],
  },
  {
    lessonId: 'prem-1',
    questions: [
      {
        id: 'p1q1',
        question: 'ما وظيفة الأمر nmap؟',
        questionEn: 'What does nmap do?',
        options: ['مسح الشبكات واكتشاف الأجهزة', 'إدارة الحزم', 'تحرير النصوص', 'تصفح الإنترنت'],
        optionsEn: ['Network scanning and device discovery', 'Package management', 'Text editing', 'Web browsing'],
        correct: 0,
      },
      {
        id: 'p1q2',
        question: 'كيف تكتشف إصدارات الخدمات باستخدام nmap؟',
        questionEn: 'How do you detect service versions with nmap?',
        options: ['nmap -sP', 'nmap -sV', 'nmap -O', 'nmap -A'],
        optionsEn: ['nmap -sP', 'nmap -sV', 'nmap -O', 'nmap -A'],
        correct: 1,
      },
      {
        id: 'p1q3',
        question: 'ما الذي يكشفه أمر whois؟',
        questionEn: 'What does whois reveal?',
        options: ['معلومات عن مالك النطاق', 'عنوان IP فقط', 'كلمة مرور الموقع', 'رسائل البريد'],
        optionsEn: ['Domain owner information', 'IP address only', 'Site password', 'Email messages'],
        correct: 0,
      },
      {
        id: 'p1q4',
        question: 'أي أمر يستخدم لاستعلام سجلات DNS؟',
        questionEn: 'Which command queries DNS records?',
        options: ['dns', 'nslookup', 'dig', 'resolve'],
        optionsEn: ['dns', 'nslookup', 'dig', 'resolve'],
        correct: 2,
      },
      {
        id: 'p1q5',
        question: 'لماذا يسمى netcat "سكين الجيش السويسري"؟',
        questionEn: 'Why is netcat called the "Swiss army knife"?',
        options: ['لأنه باهظ الثمن', 'لتعدد استخداماته', 'لأنه صغير الحجم', 'لأنه سويسري الصنع'],
        optionsEn: ['Because it is expensive', 'For its versatility', 'Because it is small', 'Because it is Swiss-made'],
        correct: 1,
      },
    ],
  },
  {
    lessonId: 'prem-2',
    questions: [
      {
        id: 'p2q1',
        question: 'ما وظيفة tcpdump؟',
        questionEn: 'What does tcpdump do?',
        options: ['مسح المنافذ', 'التقاط وتحليل حزم الشبكة', 'إدارة جدار الحماية', 'تشفير البيانات'],
        optionsEn: ['Port scanning', 'Packet capture and analysis', 'Firewall management', 'Data encryption'],
        correct: 1,
      },
      {
        id: 'p2q2',
        question: 'كيف تلتقط حزم HTTP فقط باستخدام tcpdump؟',
        questionEn: 'How do you capture only HTTP packets with tcpdump?',
        options: ['tcpdump http', 'tcpdump port 80', 'tcpdump proto http', 'tcpdump -http'],
        optionsEn: ['tcpdump http', 'tcpdump port 80', 'tcpdump proto http', 'tcpdump -http'],
        correct: 1,
      },
      {
        id: 'p2q3',
        question: 'ماذا يكشف arp-scan؟',
        questionEn: 'What does arp-scan reveal?',
        options: ['الخدمات على الخادم', 'الأجهزة المتصلة على الشبكة المحلية', 'الثغرات الأمنية', 'كلمات المرور'],
        optionsEn: ['Services on the server', 'Devices on the local network', 'Security vulnerabilities', 'Passwords'],
        correct: 1,
      },
      {
        id: 'p2q4',
        question: 'أي أداة تُستخدم لإنشاء exploits؟',
        questionEn: 'Which tool is used to create exploits?',
        options: ['Wireshark', 'Metasploit', 'tcpdump', 'arp-scan'],
        optionsEn: ['Wireshark', 'Metasploit', 'tcpdump', 'arp-scan'],
        correct: 1,
      },
      {
        id: 'p2q5',
        question: 'كيف تفحص المنافذ باستخدام netcat؟',
        questionEn: 'How do you scan ports with netcat?',
        options: ['nc -p 22', 'nc -zv host port', 'nc -scan host', 'nc --port host'],
        optionsEn: ['nc -p 22', 'nc -zv host port', 'nc -scan host', 'nc --port host'],
        correct: 1,
      },
    ],
  },
  {
    lessonId: 'prem-3',
    questions: [
      {
        id: 'p3q1',
        question: 'ما وظيفة Nikto؟',
        questionEn: 'What does Nikto do?',
        options: ['مسح خوادم الويب بحثاً عن الثغرات', 'إدارة قواعد البيانات', 'تحرير HTML', 'تصميم مواقع'],
        optionsEn: ['Scans web servers for vulnerabilities', 'Database management', 'HTML editing', 'Web design'],
        correct: 0,
      },
      {
        id: 'p3q2',
        question: 'ما نوع الثغرات التي يستغلها SQLMap؟',
        questionEn: 'What type of vulnerabilities does SQLMap exploit?',
        options: ['XSS', 'حقن SQL', 'CSRF', 'SSRF'],
        optionsEn: ['XSS', 'SQL Injection', 'CSRF', 'SSRF'],
        correct: 1,
      },
      {
        id: 'p3q3',
        question: 'ما وظيفة Searchsploit؟',
        questionEn: 'What does Searchsploit do?',
        options: ['يبحث في Google', 'يبحث في Exploit-DB عن ثغرات', 'يبحث في الملفات', 'يبحث عن شبكات'],
        optionsEn: ['Searches Google', 'Searches Exploit-DB for vulnerabilities', 'Searches files', 'Searches networks'],
        correct: 1,
      },
      {
        id: 'p3q4',
        question: 'أي header أمني يكتشف Nikto عادةً عدم وجوده؟',
        questionEn: 'Which security header does Nikto often detect as missing?',
        options: ['X-XSS-Protection', 'Content-Type', 'Server', 'Location'],
        optionsEn: ['X-XSS-Protection', 'Content-Type', 'Server', 'Location'],
        correct: 0,
      },
      {
        id: 'p3q5',
        question: 'ما معلمة SQLMap التي تجعله يعمل تلقائياً؟',
        questionEn: 'Which SQLMap parameter makes it run automatically?',
        options: ['--auto', '--batch', '--yes', '--force'],
        optionsEn: ['--auto', '--batch', '--yes', '--force'],
        correct: 1,
      },
    ],
  },
  {
    lessonId: 'prem-4',
    questions: [
      {
        id: 'p4q1',
        question: 'ما هي الهندسة الاجتماعية؟',
        questionEn: 'What is social engineering?',
        options: ['اختراق الأنظمة تقنياً', 'استغلال العامل البشري', 'برمجة التطبيقات', 'تشفير البيانات'],
        optionsEn: ['Technical system hacking', 'Exploiting the human factor', 'Application programming', 'Data encryption'],
        correct: 1,
      },
      {
        id: 'p4q2',
        question: 'ما اختصار SET؟',
        questionEn: 'What does SET stand for?',
        options: ['Secure Encryption Tool', 'Social Engineering Toolkit', 'System Exploit Tool', 'Security Edit Tool'],
        optionsEn: ['Secure Encryption Tool', 'Social Engineering Toolkit', 'System Exploit Tool', 'Security Edit Tool'],
        correct: 1,
      },
      {
        id: 'p4q3',
        question: 'ماذا تستهدف أداة BeEF؟',
        questionEn: 'What does BeEF target?',
        options: ['الخوادم', 'قواعد البيانات', 'متصفح الضحية', 'الشبكات اللاسلكية'],
        optionsEn: ['Servers', 'Databases', 'Victim browser', 'Wireless networks'],
        correct: 2,
      },
      {
        id: 'p4q4',
        question: 'أي من هذه هجمات SET؟',
        questionEn: 'Which of these is a SET attack?',
        options: ['SQL Injection', 'Spear-Phishing', 'DDoS', 'ARP Spoofing'],
        optionsEn: ['SQL Injection', 'Spear-Phishing', 'DDoS', 'ARP Spoofing'],
        correct: 1,
      },
      {
        id: 'p4q5',
        question: 'ما أفضل وسيلة للوقاية من الهندسة الاجتماعية؟',
        questionEn: 'What is the best defense against social engineering?',
        options: ['جدار ناري قوي', 'التدريب والتوعية', 'برامج مكافحة الفيروسات', 'تشفير القرص الصلب'],
        optionsEn: ['Strong firewall', 'Training and awareness', 'Antivirus software', 'Disk encryption'],
        correct: 1,
      },
    ],
  },
  {
    lessonId: 'prem-5',
    questions: [
      {
        id: 'p5q1',
        question: 'ما وظيفة airmon-ng؟',
        questionEn: 'What does airmon-ng do?',
        options: ['كسر تشفير WPA', 'تفعيل وضع المراقبة على الواجهة اللاسلكية', 'التقاط الحزم', 'حقن الحزم'],
        optionsEn: ['Crack WPA encryption', 'Enable monitor mode on wireless interface', 'Capture packets', 'Inject packets'],
        correct: 1,
      },
      {
        id: 'p5q2',
        question: 'أي أداة تكتشف الشبكات المخفية؟',
        questionEn: 'Which tool detects hidden networks?',
        options: ['Aircrack-ng', 'Kismet', 'Aireplay-ng', 'Airgeddon'],
        optionsEn: ['Aircrack-ng', 'Kismet', 'Aireplay-ng', 'Airgeddon'],
        correct: 1,
      },
      {
        id: 'p5q3',
        question: 'ما أفضل بروتوكول أمان للشبكات اللاسلكية؟',
        questionEn: 'What is the best wireless security protocol?',
        options: ['WEP', 'WPA', 'WPA2', 'WPA3'],
        optionsEn: ['WEP', 'WPA', 'WPA2', 'WPA3'],
        correct: 3,
      },
      {
        id: 'p5q4',
        question: 'لماذا يجب تعطيل WPS؟',
        questionEn: 'Why should WPS be disabled?',
        options: ['لأنه يبطئ الشبكة', 'لأنه غير آمن وسهل الاختراق', 'لأنه يستهلك طاقة', 'لأنه قديم'],
        optionsEn: ['It slows the network', 'It is insecure and easy to crack', 'It consumes power', 'It is outdated'],
        correct: 1,
      },
      {
        id: 'p5q5',
        question: 'أي أداة من Aircrack-ng تستخدم لحقن الحزم؟',
        questionEn: 'Which Aircrack-ng tool injects packets?',
        options: ['airodump-ng', 'aireplay-ng', 'aircrack-ng', 'airmon-ng'],
        optionsEn: ['airodump-ng', 'aireplay-ng', 'aircrack-ng', 'airmon-ng'],
        correct: 1,
      },
    ],
  },
  {
    lessonId: 'prem-6',
    questions: [
      {
        id: 'p6q1',
        question: 'ما وظيفة iptables؟',
        questionEn: 'What does iptables do?',
        options: ['إدارة الشبكات اللاسلكية', 'تصفية الحزم وجدار الحماية', 'إدارة المستخدمين', 'تثبيت البرامج'],
        optionsEn: ['Wireless network management', 'Packet filtering and firewall', 'User management', 'Software installation'],
        correct: 1,
      },
      {
        id: 'p6q2',
        question: 'كيف تمنع SSH من جميع المصادر باستثناء الشبكة المحلية؟',
        questionEn: 'How do you block SSH from all except local network?',
        options: ['iptables -A INPUT -p tcp --dport 22 -j ACCEPT', 'iptables مع قواعد السماح من 192.168.1.0/24 والرفض للباقي', 'iptables -A INPUT -p tcp --dport 22 -j DROP', 'لا يمكن'],
        optionsEn: ['iptables -A INPUT -p tcp --dport 22 -j ACCEPT', 'iptables with allow from 192.168.1.0/24 and drop rest', 'iptables -A INPUT -p tcp --dport 22 -j DROP', 'Not possible'],
        correct: 1,
      },
      {
        id: 'p6q3',
        question: 'ما وظيفة fail2ban؟',
        questionEn: 'What does fail2ban do?',
        options: ['يمنع هجمات التخمين', 'يشفر الاتصالات', 'ينسخ الملفات', 'يراقب درجة الحرارة'],
        optionsEn: ['Prevents brute force attacks', 'Encrypts connections', 'Copies files', 'Monitors temperature'],
        correct: 0,
      },
      {
        id: 'p6q4',
        question: 'ما الذي يكتشفه rkhunter؟',
        questionEn: 'What does rkhunter detect?',
        options: ['الفيروسات فقط', 'الجذور الخفية والبرامج الضارة', 'الثغرات في تطبيقات الويب', 'مشاكل الشبكة'],
        optionsEn: ['Viruses only', 'Rootkits and malware', 'Web app vulnerabilities', 'Network issues'],
        correct: 1,
      },
      {
        id: 'p6q5',
        question: 'أي أمر لتحديث النظام في دبيان/أوبونتو؟',
        questionEn: 'Which command updates the system on Debian/Ubuntu?',
        options: ['sudo apt update && sudo apt upgrade', 'sudo yum update', 'sudo pacman -Syu', 'sudo dnf update'],
        optionsEn: ['sudo apt update && sudo apt upgrade', 'sudo yum update', 'sudo pacman -Syu', 'sudo dnf update'],
        correct: 0,
      },
    ],
  },
  {
    lessonId: 'free-7',
    questions: [
      {
        id: 'f7q1',
        question: 'ما معنى HTML؟',
        questionEn: 'What does HTML stand for?',
        options: ['HyperText Markup Language', 'Home Tool Markup Language', 'HyperLinks Markup Language', 'HighText Machine Language'],
        optionsEn: ['HyperText Markup Language', 'Home Tool Markup Language', 'HyperLinks Markup Language', 'HighText Machine Language'],
        correct: 0,
      },
      {
        id: 'f7q2',
        question: 'أي وسم يستخدم لإنشاء عنوان رئيسي؟',
        questionEn: 'Which tag is used for a main heading?',
        options: ['&lt;head&gt;', '&lt;h1&gt;', '&lt;heading&gt;', '&lt;title&gt;'],
        optionsEn: ['&lt;head&gt;', '&lt;h1&gt;', '&lt;heading&gt;', '&lt;title&gt;'],
        correct: 1,
      },
      {
        id: 'f7q3',
        question: 'أي وسم يستخدم لإدراج صورة؟',
        questionEn: 'Which tag is used to insert an image?',
        options: ['&lt;img&gt;', '&lt;image&gt;', '&lt;src&gt;', '&lt;picture&gt;'],
        optionsEn: ['&lt;img&gt;', '&lt;image&gt;', '&lt;src&gt;', '&lt;picture&gt;'],
        correct: 0,
      },
      {
        id: 'f7q4',
        question: 'أي وسم ينشئ رابطاً تشعبيًا؟',
        questionEn: 'Which tag creates a hyperlink?',
        options: ['&lt;link&gt;', '&lt;a&gt;', '&lt;href&gt;', '&lt;url&gt;'],
        optionsEn: ['&lt;link&gt;', '&lt;a&gt;', '&lt;href&gt;', '&lt;url&gt;'],
        correct: 1,
      },
      {
        id: 'f7q5',
        question: 'ما الفرق بين &lt;div&gt; و &lt;span&gt;؟',
        questionEn: 'What is the difference between &lt;div&gt; and &lt;span&gt;?',
        options: ['div عنصر كتلة و span عنصر سطر', 'لا فرق', 'span عنصر كتلة و div عنصر سطر', 'كلاهما عناصر سطر'],
        optionsEn: ['div is block-level, span is inline', 'No difference', 'span is block-level, div is inline', 'Both are inline'],
        correct: 0,
      },
    ],
  },
  {
    lessonId: 'free-8',
    questions: [
      {
        id: 'f8q1',
        question: 'كيف يتم تطبيق CSS على عنصر HTML؟',
        questionEn: 'How is CSS applied to an HTML element?',
        options: ['باستخدام الخاصية style', 'باستخدام الوسم css', 'باستخدام الخاصية design', 'لا يمكن'],
        optionsEn: ['Using the style attribute', 'Using the css tag', 'Using the design attribute', 'Not possible'],
        correct: 0,
      },
      {
        id: 'f8q2',
        question: 'ما الخاصية التي تغير لون النص؟',
        questionEn: 'Which property changes text color?',
        options: ['text-color', 'font-color', 'color', 'foreground'],
        optionsEn: ['text-color', 'font-color', 'color', 'foreground'],
        correct: 2,
      },
      {
        id: 'f8q3',
        question: 'كيف تختار عنصر بواسطة class في CSS؟',
        questionEn: 'How do you select an element by class in CSS?',
        options: ['.className', '#className', '*className', 'className'],
        optionsEn: ['.className', '#className', '*className', 'className'],
        correct: 0,
      },
      {
        id: 'f8q4',
        question: 'ما الخاصية التي تجعل العناصر تظهر بجانب بعضها؟',
        questionEn: 'Which property makes elements appear side by side?',
        options: ['display: block', 'display: inline', 'display: flex', 'display: grid'],
        optionsEn: ['display: block', 'display: inline', 'display: flex', 'display: grid'],
        correct: 2,
      },
      {
        id: 'f8q5',
        question: 'ما هي قاعدة CSS التي تطبق عند تمرير الماوس؟',
        questionEn: 'Which CSS rule applies on mouse hover?',
        options: [':click', ':hover', ':over', ':focus'],
        optionsEn: [':click', ':hover', ':over', ':focus'],
        correct: 1,
      },
    ],
  },
  {
    lessonId: 'prem-7',
    questions: [
      {
        id: 'p7q1',
        question: 'كيف تعرف متغير في JavaScript؟',
        questionEn: 'How do you declare a variable in JavaScript?',
        options: ['var name', 'variable name', 'v name', '$name'],
        optionsEn: ['var name', 'variable name', 'v name', '$name'],
        correct: 0,
      },
      {
        id: 'p7q2',
        question: 'أي دالة تطبع نصاً في console؟',
        questionEn: 'Which function prints text to the console?',
        options: ['print()', 'log()', 'console.log()', 'echo()'],
        optionsEn: ['print()', 'log()', 'console.log()', 'echo()'],
        correct: 2,
      },
      {
        id: 'p7q3',
        question: 'ما نوع القيمة التي تعيدها typeof []؟',
        questionEn: 'What type does typeof [] return?',
        options: ['array', 'object', 'list', 'undefined'],
        optionsEn: ['array', 'object', 'list', 'undefined'],
        correct: 1,
      },
      {
        id: 'p7q4',
        question: 'كيف تكتب دالة في JavaScript؟',
        questionEn: 'How do you write a function in JavaScript?',
        options: ['function = myFunc()', 'function myFunc()', 'def myFunc()', 'func myFunc()'],
        optionsEn: ['function = myFunc()', 'function myFunc()', 'def myFunc()', 'func myFunc()'],
        correct: 1,
      },
      {
        id: 'p7q5',
        question: 'ما الفرق بين == و ===؟',
        questionEn: 'What is the difference between == and ===?',
        options: ['لا فرق', '== يقارن القيمة فقط، === يقارن القيمة والنوع', '=== يقارن القيمة فقط', '== يقارن القيمة والنوع'],
        optionsEn: ['No difference', '== compares value only, === compares value and type', '=== compares value only', '== compares value and type'],
        correct: 1,
      },
    ],
  },
  {
    lessonId: 'prem-8',
    questions: [
      {
        id: 'p8q1',
        question: 'كيف تطبع "Hello" في بايثون؟',
        questionEn: 'How do you print "Hello" in Python?',
        options: ['print("Hello")', 'echo("Hello")', 'log("Hello")', 'printf("Hello")'],
        optionsEn: ['print("Hello")', 'echo("Hello")', 'log("Hello")', 'printf("Hello")'],
        correct: 0,
      },
      {
        id: 'p8q2',
        question: 'أي نوع بيانات تستخدم للأرقام العشرية؟',
        questionEn: 'Which data type is used for decimal numbers?',
        options: ['int', 'float', 'decimal', 'number'],
        optionsEn: ['int', 'float', 'decimal', 'number'],
        correct: 1,
      },
      {
        id: 'p8q3',
        question: 'كيف تنشئ قائمة (List) في بايثون؟',
        questionEn: 'How do you create a List in Python?',
        options: ['list = (1, 2, 3)', 'list = [1, 2, 3]', 'list = {1, 2, 3}', 'list = <1, 2, 3>'],
        optionsEn: ['list = (1, 2, 3)', 'list = [1, 2, 3]', 'list = {1, 2, 3}', 'list = <1, 2, 3>'],
        correct: 1,
      },
      {
        id: 'p8q4',
        question: 'ما وظيفة الحلقة for في بايثون؟',
        questionEn: 'What does a for loop do in Python?',
        options: ['تكرر كود عدداً محدداً من المرات', 'تتحقق من شرط', 'تعرف دالة', 'تنهي البرنامج'],
        optionsEn: ['Repeats code a specific number of times', 'Checks a condition', 'Defines a function', 'Exits the program'],
        correct: 0,
      },
      {
        id: 'p8q5',
        question: 'كيف تعرف دالة في بايثون؟',
        questionEn: 'How do you define a function in Python?',
        options: ['function myFunc():', 'def myFunc():', 'func myFunc():', 'define myFunc():'],
        optionsEn: ['function myFunc():', 'def myFunc():', 'func myFunc():', 'define myFunc():'],
        correct: 1,
      },
    ],
  },
];

export const getQuizData = (lessonId: string): QuizData | undefined =>
  QUIZ_DATA.find((q) => q.lessonId === lessonId);

export const PASS_THRESHOLD = 95;
export const TOTAL_LESSONS = 16;
